models:
- hyperparameters:
    criterion: entropy
    max_depth: 8
    min_samples_leaf: 7
    n_estimators: 400
  name: Random Forest
  negative_log_loss: -0.21977023554452108
- hyperparameters:
    criterion: gini
    max_depth: 6
    min_samples_leaf: 10
  name: Decision Tree
  negative_log_loss: -0.4094425836985048
- hyperparameters:
    C: 10
    max_iter: 200
    solver: lbfgs
  name: Logistic Regression
  negative_log_loss: -0.3275133280867423
- hyperparameters:
    gamma: 0.3
    learning_rate: 0.1
    max_depth: 7
    n_estimators: 400
    reg_alpha: 0.1
    reg_lambda: 1
  name: XGBoost
  negative_log_loss: -0.19487799322213456
