models:
- hyperparameters:
    criterion: gini
    max_depth: 8
    min_samples_leaf: 7
    n_estimators: 400
  name: Random Forest
  negative_log_loss: -0.39641570389978187
- hyperparameters:
    criterion: gini
    max_depth: 6
    min_samples_leaf: 10
  name: Decision Tree
  negative_log_loss: -0.5881149087760205
- hyperparameters:
    C: 1
    max_iter: 100
    solver: newton-cg
  name: Logistic Regression
  negative_log_loss: -0.5886442214014942
- hyperparameters:
    gamma: 0.2
    learning_rate: 0.1
    max_depth: 9
    n_estimators: 500
    reg_alpha: 0
    reg_lambda: 1
  name: XGBoost
  negative_log_loss: -0.2282463619810195
