# configuration of steps  
steps:
  model_trainer:
    parameters:
      name: model
  promote_with_metric_compare:
    parameters:
      mlflow_model_name: model
  notify_on_success:
    parameters:
      notify_on_success: False


# pipeline level extra configurations
extra:
  notify_on_failure: True
# pipeline level parameters
parameters:
  target_env: staging
  # This set contains all the model configurations that you want 
  # to evaluate during the hyperparameter tuning stage.
  model_search_space:
    random_forest:
      model_package: sklearn.ensemble
      model_class: RandomForestClassifier
      search_grid:
        criterion:
          - gini
          - entropy
        max_depth:
          - 2
          - 4
          - 6
          - 8
          - 10
          - 12
        min_samples_leaf:
          range:
            start: 1
            end: 10
        n_estimators:
          range:
            start: 50
            end: 500
            step: 25

    decision_tree:
      model_package: sklearn.tree
      model_class: DecisionTreeClassifier
      search_grid:
        criterion:
          - gini
          - entropy
        max_depth:
          - 2
          - 4
          - 6
          - 8
          - 10
          - 12
        min_samples_leaf:
          range:
            start: 1
            end: 10


    logistic_regression:
      model_package: sklearn.linear_model
      model_class: LogisticRegression
      search_grid:
        C:
          - 0.1
          - 1
          - 10
          - 100
        solver:
          - newton-cg
          - lbfgs
          - liblinear
          - sag
          - saga
        max_iter:
          - 100
          - 200
          - 500
    xgboost:
      model_package: xgboost
      model_class: XGBClassifier
      search_grid:
        n_estimators:
          range:
            start: 50
            end: 500
            step: 50
        max_depth:
          - 3
          - 5
          - 7
          - 9
          - 12
        learning_rate:
          - 0.01
          - 0.05
          - 0.1
          - 0.2
        subsample:
          - 0.6
          - 0.8
          - 1.0
        colsample_bytree:
          - 0.6
          - 0.8
          - 1.0
        gamma:
          - 0
          - 0.1
          - 0.2
          - 0.3
        reg_alpha:
          - 0
          - 0.01
          - 0.1
        reg_lambda:
          - 1
          - 0.1
          - 0.01
    mlp:
      model_package: sklearn.neural_network
      model_class: MLPClassifier
      search_grid:
        hidden_layer_sizes:
          - (50,)
          - (100,)
          - (100, 50)
          - (50, 100)
          - (100, 100)
        activation:
          - relu
          - tanh
          - logistic
        solver:
          - adam
          - sgd
          - lbfgs
        alpha:
          - 0.0001
          - 0.001
          - 0.01
          - 0.1
        learning_rate:
          - constant
          - adaptive
        max_iter:
          - 200
          - 500
          - 1000
        early_stopping:
          - True
          - False
