models:
- hyperparameters:
    criterion: entropy
    max_depth: 8
    min_samples_leaf: 7
    n_estimators: 400
  name: Random Forest
  negative_log_loss: -0.47633009145220057
- hyperparameters:
    criterion: gini
    max_depth: 6
    min_samples_leaf: 10
  name: Decision Tree
  negative_log_loss: -0.7395808340456078
- hyperparameters:
    C: 10
    max_iter: 100
    solver: lbfgs
  name: Logistic Regression
  negative_log_loss: -0.47627586579100234
- hyperparameters:
    gamma: 0.3
    learning_rate: 0.1
    max_depth: 7
    n_estimators: 400
    reg_alpha: 0.01
    reg_lambda: 1
  name: XGBoost
  negative_log_loss: -0.4929849447702798
