models:
- hyperparameters:
    criterion: gini
    max_depth: 8
    min_samples_leaf: 7
    n_estimators: 400
  name: Random Forest
  negative_log_loss: -0.6562527115895467
- hyperparameters:
    criterion: gini
    max_depth: 6
    min_samples_leaf: 7
  name: Decision Tree
  negative_log_loss: -0.7025390047938291
- hyperparameters:
    C: 1
    max_iter: 100
    solver: lbfgs
  name: Logistic Regression
  negative_log_loss: -0.6749170177389685
- hyperparameters:
    gamma: 0.1
    learning_rate: 0.1
    max_depth: 7
    n_estimators: 400
    reg_alpha: 0.01
    reg_lambda: 1
  name: XGBoost
  negative_log_loss: -0.6878268113697894
